# Author: Lucas Vilas-Boas
# Year: 2025
# Repo: https://github.com/lucoiso/luvk_example

# GLM Options
SET(GLM_BUILD_TESTS OFF CACHE BOOL "" FORCE)
SET(GLM_BUILD_INSTALL OFF CACHE BOOL "" FORCE)
SET(GLM_BUILD_LIBRARY OFF CACHE BOOL "" FORCE)
SET(GLM_ENABLE_CXX_17 OFF CACHE BOOL "" FORCE)
SET(GLM_ENABLE_CXX_20 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_SSE2 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_SSE3 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_SSSE3 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_SSE4_1 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_SSE4_2 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_AVX ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_AVX2 ON CACHE BOOL "" FORCE)
SET(GLM_ENABLE_SIMD_NEON ON CACHE BOOL "" FORCE)
SET(GLM_FORCE_PURE OFF CACHE BOOL "" FORCE)

FETCHCONTENT_DECLARE(glm
                     GIT_REPOSITORY https://github.com/g-truc/glm.git
                     GIT_TAG 1.0.2
)
FETCHCONTENT_MAKEAVAILABLE(glm)