# Author: Lucas Vilas-Boas
# Year: 2025
# Repo: https://github.com/lucoiso/luvk_example

IF (BUILD_SHARED_LIBS)
    SET(SDL_SHARED ON CACHE BOOL "" FORCE)
    SET(SDL_STATIC OFF CACHE BOOL "" FORCE)
ELSE ()
    SET(SDL_SHARED OFF CACHE BOOL "" FORCE)
    SET(SDL_STATIC ON CACHE BOOL "" FORCE)
ENDIF ()

SET(SDL_TESTS OFF CACHE BOOL "" FORCE)
SET(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
SET(SDL_DISABLE_INSTALL OFF CACHE BOOL "" FORCE)
SET(SDL_DISABLE_INSTALL_DOCS OFF CACHE BOOL "" FORCE)
SET(SDL_INSTALL_TESTS OFF CACHE BOOL "" FORCE)

SET(SDL_VIDEO ON CACHE BOOL "" FORCE)
SET(SDL_VULKAN ON CACHE BOOL "" FORCE)
SET(SDL_DIRECTX OFF CACHE BOOL "" FORCE)
SET(SDL_OPENGLES OFF CACHE BOOL "" FORCE)

SET(SDL_AUDIO OFF CACHE BOOL "" FORCE)
SET(SDL_GPU OFF CACHE BOOL "" FORCE)
SET(SDL_RENDER OFF CACHE BOOL "" FORCE)
SET(SDL_CAMERA OFF CACHE BOOL "" FORCE)
SET(SDL_JOYSTICK OFF CACHE BOOL "" FORCE)
SET(SDL_HAPTIC OFF CACHE BOOL "" FORCE)
SET(SDL_HIDAPI OFF CACHE BOOL "" FORCE)
SET(SDL_POWER OFF CACHE BOOL "" FORCE)
SET(SDL_SENSOR OFF CACHE BOOL "" FORCE)
SET(SDL_DIALOG OFF CACHE BOOL "" FORCE)

FETCHCONTENT_DECLARE(sdl3
                     GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
                     GIT_TAG release-3.2.28
)
FETCHCONTENT_MAKEAVAILABLE(sdl3)