# Author: Lucas Vilas-Boas
# Year: 2025
# Repo: https://github.com/lucoiso/luvk

MACRO(CORE_DEFINE_MODULE_API LIBRARY_NAME)
    STRING(TOUPPER ${LIBRARY_NAME} BUILD_DLL_PREFIX)
    GET_TARGET_PROPERTY(TARGET_TYPE ${LIBRARY_NAME} TYPE)

    IF(TARGET_TYPE STREQUAL "SHARED_LIBRARY")
        IF(WIN32)
            TARGET_COMPILE_DEFINITIONS(${LIBRARY_NAME} PRIVATE "${BUILD_DLL_PREFIX}_API=__declspec(dllexport)")
            TARGET_COMPILE_DEFINITIONS(${LIBRARY_NAME} INTERFACE "${BUILD_DLL_PREFIX}_API=__declspec(dllimport)")
        ELSE()
            TARGET_COMPILE_DEFINITIONS(${LIBRARY_NAME} PRIVATE "${BUILD_DLL_PREFIX}_API=__attribute__((visibility(\"default\")))")
            TARGET_COMPILE_DEFINITIONS(${LIBRARY_NAME} INTERFACE "${BUILD_DLL_PREFIX}_API=")
        ENDIF()
    ELSE()
        TARGET_COMPILE_DEFINITIONS(${LIBRARY_NAME} PUBLIC "${BUILD_DLL_PREFIX}_API=")
    ENDIF()
ENDMACRO()